# frr-config/frr.conf
!
! Configuracion basica para el demonio zebra
!
hostname docker-router
password frr
enable password frr

log stdout
!
line vty
!

!
! Configuracion del protocolo de enrutamiento (Ejemplo RIP)
!
# router rip
#  version 2
#  ! Habilitar RIP en una o mas interfaces
#  ! Las interfaces como eth0, eth1, etc., seran las interfaces del contenedor
#  network eth0
#  network eth1
#  ! Opcionalmente, redistribuir rutas conectadas
#  redistribute connected
!
! Configuracion del protocolo de enrutamiento (Ejemplo IS-IS - si usas IS-IS en lugar de RIP)
!
router isis FOO
 net 49.0001.1920.1680.0010.00
 is-type level-2-only
