# auth:
#   public:
#     community: public
#     version: 2
modules:
  linux_router:
    version: 2
    auth:
      community: public
    walk:
      - 1.3.6.1.2.1.1.5.0 # Identity OID
      - 1.3.6.1.2.1.2.2.1.2.1 # Interface Name OID
      - 1.3.6.1.2.1.31.1.1.1.6.1 # Bytes In OID
      - 1.3.6.1.2.1.31.1.1.1.10.1 # Bytes Out OID
    # walk_params:
    #   public:
    #     auth:
    #       community: public
    #     version: 2
    metrics:
      - name: identity
        oid: 1.3.6.1.2.1.1.5.0
        type: DisplayString
      - name: interfaceName
        oid: 1.3.6.1.2.1.2.2.1.2.1
        type: DisplayString
      - name: bytesIn
        oid: 1.3.6.1.2.1.31.1.1.1.6.1
        type: DisplayString
      - name: bytesOut
        oid: 1.3.6.1.2.1.31.1.1.1.10.1
        type: DisplayString

